# Netlify deployment configuration
[build]
  publish = "dist"
  command = "npm run build:production"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
  
# Production context
[context.production]
  command = "npm run build:production"
  
[context.production.environment]
  VITE_NODE_ENV = "production"
  VITE_ENABLE_SERVICE_WORKER = "true"
  VITE_ENABLE_PERFORMANCE_MONITORING = "true"
  
# Staging context (deploy-preview)
[context.deploy-preview]
  command = "npm run build"
  
[context.deploy-preview.environment]
  VITE_NODE_ENV = "staging"
  VITE_ENABLE_SERVICE_WORKER = "false"
  VITE_ENABLE_PERFORMANCE_MONITORING = "false"

# Branch deploys
[context.branch-deploy]
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    
# HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# API routes (if using Netlify Functions)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Edge functions (if using)
[[edge_functions]]
  function = "geolocation"
  path = "/api/location"

# Forms (if using Netlify Forms)
# Uncomment if you have contact forms
# [[forms]]
#   name = "contact"
#   action = "/contact"
#   method = "POST"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.95
    best-practices = 0.9
    seo = 0.9
    
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://wellheadequipment.com"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing"
    ]