name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install and Build
      run: |
        cd wellhead-modern
        npm install
        NODE_ENV=production npm run build

    - uses: actions/configure-pages@v4
    
    - uses: actions/upload-pages-artifact@v3
      with:
        path: wellhead-modern/dist

    - uses: actions/deploy-pages@v4
      id: deployment